FPTTraining0/Models/Trainer.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace FPTTraining0.Models
{
    public class Trainer
    {
        public int Id { get; set; }
        [Required]
        [DisplayName("Trainer Name")]
        public string Name { get; set; }
        [Required]
        [DisplayName("Trainer Email")]
        public string TrainerEmail { get; set; }
        [Required]
        [DisplayName("Password Email")]
        public string PassEmail { get; set; }
        [Required]
        public int MajorId { get; set; }
        public Major Major { get; set; }
    }
}

FPTTraining0/Controllers/TrainersController.cs
using FPTTraining0.Models;
using FPTTraining0.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Data.Entity;

namespace FPTTraining0.Controllers
{
    public class TrainersController : Controller
    {
		private ApplicationDbContext _context;
		public TrainersController()
		{
			_context = new ApplicationDbContext();
		}
		// GET: Trainer
		[HttpGet]
		public ActionResult Index(string searchString)
		{
			var trainers = _context.Trainers
			.Include(p => p.Major);

			if (!String.IsNullOrEmpty(searchString))
			{
				trainers = trainers.Where(
					s => s.Name.Contains(searchString) ||
					s.Major.Name.Contains(searchString));
			}

			return View(trainers.ToList());
		}

		[HttpGet]
		[Authorize(Roles = "admin")]
		public ActionResult Create()
		{
			var viewModel = new TrainerMajorViewModel
			{
				Majors = _context.Majors.ToList()
			};
			return View(viewModel);
		}

		[HttpPost]
		[Authorize(Roles = "admin")]
		public ActionResult Create(Trainer trainer)
		{
			if (!ModelState.IsValid)
			{
				return View();
			}

			if (_context.Trainers.Any(p => p.Name.Contains(trainer.Name)))
			{
				ModelState.AddModelError("Name", "Trainer Name Already Exists.");
				return View();
			}

			var newTrainer = new Trainer
			{
				Name = trainer.Name,
				TrainerEmail = trainer.TrainerEmail,
				PassEmail = trainer.PassEmail,
				MajorId = trainer.MajorId
			};

			_context.Trainers.Add(newTrainer);
			_context.SaveChanges();

			return RedirectToAction("Index");
		}

		[HttpGet]
		[Authorize(Roles = "admin")]

		public ActionResult Delete(int id)
		{
			var trainerInDb = _context.Trainers.SingleOrDefault(p => p.Id == id);

			if (trainerInDb == null)
			{
				return HttpNotFound();
			}

			_context.Trainers.Remove(trainerInDb);
			_context.SaveChanges();

			return RedirectToAction("Index");
		}

		[HttpGet]
		[Authorize(Roles = "admin")]

		public ActionResult Edit(int id)
		{
			var trainerInDb = _context.Trainers.SingleOrDefault(p => p.Id == id);

			if (trainerInDb == null)
			{
				return HttpNotFound();
			}

			var viewModel = new TrainerMajorViewModel
			{
				Trainer = trainerInDb,
				Majors = _context.Majors.ToList()
			};

			return View(viewModel);
		}

		[HttpPost]
		[Authorize(Roles = "admin")]

		public ActionResult Edit(Trainer trainer)
		{
			if (!ModelState.IsValid)
			{
				return View();
			}

			var trainerInDb = _context.Trainers.SingleOrDefault(p => p.Id == trainer.Id);

			if (trainerInDb == null)
			{
				return HttpNotFound();
			}

			trainerInDb.Name = trainer.Name;
			trainerInDb.TrainerEmail = trainer.TrainerEmail;
			trainerInDb.PassEmail = trainer.PassEmail;
			trainerInDb.MajorId = trainer.MajorId;
			_context.SaveChanges();

			return RedirectToAction("Index");
		}
	}
}

FPTTraining0/Views/Trainers/Create.cshtml
@model FPTTraining0.ViewModels.TrainerMajorViewModel

@{
    ViewBag.Title = "Create";
}

<h2>Create a new Trainer</h2>

@Html.ValidationSummary(false, "", new { @class = "text-danger" })

@using (Html.BeginForm("Create", "Trainers", FormMethod.Post))
{
    <div class="form-group">
        @Html.LabelFor(p => p.Trainer.Name)
        @Html.TextBoxFor(p => p.Trainer.Name, new { @class = "form-control" })
        @Html.ValidationMessageFor(p => p.Trainer.Name, "", new { @class = "text-danger" })
    </div>
    <div class="form-group">
        @Html.LabelFor(p => p.Trainer.TrainerEmail)
        @Html.TextBoxFor(p => p.Trainer.TrainerEmail, new { @class = "form-control" })
        @Html.ValidationMessageFor(p => p.Trainer.TrainerEmail, "", new { @class = "text-danger" })
    </div>
    <div class="form-group">
        @Html.LabelFor(p => p.Trainer.PassEmail)
        @Html.TextBoxFor(p => p.Trainer.PassEmail, new { @class = "form-control" })
        @Html.ValidationMessageFor(p => p.Trainer.PassEmail, "", new { @class = "text-danger" })
    </div>
    <div class="form-group">
        @Html.LabelFor(p => p.Trainer.Major.Name)
        @Html.DropDownListFor(p => p.Trainer.MajorId,
         new SelectList(Model.Majors, "Id", "Name"),
         "Select Major Name",
         new { @class = "form-control" })
    </div>
    <button type="submit" class="btn btn-primary">Create</button>
}
@Html.ActionLink("Back to Index", "Index")

FPTTraining0/Views/Trainers/Edit.cshtml
@model FPTTraining0.ViewModels.TrainerMajorViewModel

@{
    ViewBag.Title = "Edit";
}

<h2>Edit Trainer</h2>

@Html.ValidationSummary(false, "", new { @class = "text-danger" })

@using (Html.BeginForm("Edit", "Trainers", FormMethod.Post))
{
    @Html.HiddenFor(p => p.Trainer.Id)
    <div class="form-group">
        @Html.LabelFor(p => p.Trainer.Name)
        @Html.EditorFor(p => p.Trainer.Name, new { htmlAttributes = new { @class = "form-control" } })
        @Html.ValidationMessageFor(p => p.Trainer.Name, "", new { @class = "text-danger" })
    </div>
    <div class="form-group">
        @Html.LabelFor(p => p.Trainer.TrainerEmail)
        @Html.EditorFor(p => p.Trainer.TrainerEmail, new { htmlAttributes = new { @class = "form-control" } })
        @Html.ValidationMessageFor(p => p.Trainer.TrainerEmail, "", new { @class = "text-danger" })
    </div>
    <div class="form-group">
        @Html.LabelFor(p => p.Trainer.PassEmail)
        @Html.TextBoxFor(p => p.Trainer.PassEmail, new { @class = "form-control" })
        @Html.ValidationMessageFor(p => p.Trainer.PassEmail, "", new { @class = "text-danger" })
    </div>
    <div class="form-group">
        @Html.LabelFor(p => p.Trainer.Major.Name)
        @Html.DropDownListFor(p => p.Trainer.MajorId,
         new SelectList(Model.Majors, "Id", "Name"),
         "Select Major Name",
         new { @class = "form-control" })
    </div>
    <button type="submit" class="btn btn-primary">Edit</button>
}
@Html.ActionLink("Back to Index", "Index")

FPTTraining0/Views/Trainers/Index.cshtml
@model IEnumerable<FPTTraining0.Models.Trainer>

@{
    ViewBag.Title = "Index";
}

<h2>Index Trainer</h2>
@Html.ActionLink("Create a new Trainer", "Create")
@using (Html.BeginForm("Index", "Trainers", FormMethod.Get))
{
    <p>
        Find by name: @Html.TextBox("SearchString")
        <input type="submit" value="Search" />
    </p>
}
<table class="table table-striped">
    <tr>
        <th>Id</th>
        <th>Trainer Name</th>
        <th>Email</th>
        <th>Password Email</th>
        <th>Major</th>
        @if (User.IsInRole("admin"))
        {
            <th>Delete</th>
            <th>Edit</th>
        }
    </tr>
    @foreach (var trainer in Model)
    {
        <tr>
            <td>@trainer.Id</td>
            <td>@trainer.Name</td>
            <td>@trainer.TrainerEmail</td>
            <td>@trainer.PassEmail</td>
            <td>@trainer.Major.Name</td>
            <td>@Html.ActionLink("Delete this trainer", "Delete", new { id = trainer.Id })</td>
            <td>@Html.ActionLink("Edit this trainer", "Edit", new { id = trainer.Id })</td>
        </tr>
    }
</table>
@Html.ActionLink("Back to home", "Index", "Home")