FPTTraining0/Models/Staff.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace FPTTraining0.Models
{
    public class Staff
    {
        public int Id { get; set; }
        [Required]
        [DisplayName("Staff Name")]
        public string Name { get; set; }
        [Required]
        [DisplayName("Staff Email")]
        public string StaffEmail { get; set; }
        [Required]
        [DisplayName("Password Email")]
        public string PassEmail { get; set; }
        [Required]
        public int DepartmentId { get; set; }
        public Department Department { get; set; }
    }
}

FPTTraining0/Controllers/StaffsController.cs
using FPTTraining0.Models;
using FPTTraining0.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Data.Entity;
namespace FPTTraining0.Controllers
{
    public class StaffsController : Controller
    {
		private ApplicationDbContext _context;
		public StaffsController()
		{
			_context = new ApplicationDbContext();
		}
		// GET: Staff
		[HttpGet]
		public ActionResult Index(string searchString)
		{
			var staffs = _context.Staffs
			.Include(p => p.Department);

			if (!String.IsNullOrEmpty(searchString))
			{
				staffs = staffs.Where(
					s => s.Name.Contains(searchString) ||
					s.Department.Name.Contains(searchString));
			}

			return View(staffs.ToList());
		}

		[HttpGet]
		[Authorize(Roles = "admin")]
		public ActionResult Create()
		{
			var viewModel = new StaffDepartmentViewModel
			{
				Departments = _context.Departments.ToList()
			};
			return View(viewModel);
		}

		[HttpPost]
		[Authorize(Roles = "admin")]
		public ActionResult Create(Staff staff)
		{
			if (!ModelState.IsValid)
			{
				return View();
			}

			if (_context.Staffs.Any(p => p.Name.Contains(staff.Name)))
			{
				ModelState.AddModelError("Name", "Staff Name Already Exists.");
				return View();
			}

			var newStaff = new Staff
			{
				Name = staff.Name,
				StaffEmail = staff.StaffEmail,
				PassEmail = staff.PassEmail,
				DepartmentId = staff.DepartmentId
			};

			_context.Staffs.Add(newStaff);
			_context.SaveChanges();

			return RedirectToAction("Index");
		}

		[HttpGet]
		[Authorize(Roles = "admin")]

		public ActionResult Delete(int id)
		{
			var staffInDb = _context.Staffs.SingleOrDefault(p => p.Id == id);

			if (staffInDb == null)
			{
				return HttpNotFound();
			}

			_context.Staffs.Remove(staffInDb);
			_context.SaveChanges();

			return RedirectToAction("Index");
		}

		[HttpGet]
		[Authorize(Roles = "admin")]

		public ActionResult Edit(int id)
		{
			var staffInDb = _context.Staffs.SingleOrDefault(p => p.Id == id);

			if (staffInDb == null)
			{
				return HttpNotFound();
			}

			var viewModel = new StaffDepartmentViewModel
			{
				Staff = staffInDb,
				Departments = _context.Departments.ToList()
			};

			return View(viewModel);
		}

		[HttpPost]
		[Authorize(Roles = "admin")]

		public ActionResult Edit(Staff staff)
		{
			if (!ModelState.IsValid)
			{
				return View();
			}

			var staffInDb = _context.Staffs.SingleOrDefault(p => p.Id == staff.Id);

			if (staffInDb == null)
			{
				return HttpNotFound();
			}

			staffInDb.Name = staff.Name;
			staffInDb.StaffEmail = staff.StaffEmail;
			staffInDb.PassEmail = staff.PassEmail;
			staffInDb.DepartmentId = staff.DepartmentId;
			_context.SaveChanges();

			return RedirectToAction("Index");
		}
	}
}

FPTTraining0/Views/Staffs/Create.cshtml
@model FPTTraining0.ViewModels.StaffDepartmentViewModel

@{
    ViewBag.Title = "Create";
}

<h2>Create a new Staff</h2>

@Html.ValidationSummary(false, "", new { @class = "text-danger" })

@using (Html.BeginForm("Create", "Staffs", FormMethod.Post))
{
    <div class="form-group">
        @Html.LabelFor(p => p.Staff.Name)
        @Html.TextBoxFor(p => p.Staff.Name, new { @class = "form-control" })
        @Html.ValidationMessageFor(p => p.Staff.Name, "", new { @class = "text-danger" })
    </div>
    <div class="form-group">
        @Html.LabelFor(p => p.Staff.StaffEmail)
        @Html.TextBoxFor(p => p.Staff.StaffEmail, new { @class = "form-control" })
        @Html.ValidationMessageFor(p => p.Staff.StaffEmail, "", new { @class = "text-danger" })
    </div>
    <div class="form-group">
        @Html.LabelFor(p => p.Staff.PassEmail)
        @Html.TextBoxFor(p => p.Staff.PassEmail, new { @class = "form-control" })
        @Html.ValidationMessageFor(p => p.Staff.PassEmail, "", new { @class = "text-danger" })
    </div>
    <div class="form-group">
        @Html.LabelFor(p => p.Staff.Department.Name)
        @Html.DropDownListFor(p => p.Staff.DepartmentId,
         new SelectList(Model.Departments, "Id", "Name"),
         "Select Department Name",
         new { @class = "form-control" })
    </div>
    <button type="submit" class="btn btn-primary">Create</button>
}
@Html.ActionLink("Back to Index", "Index")

FPTTraining0/Views/Staffs/Edit.cshtml
@model FPTTraining0.ViewModels.StaffDepartmentViewModel

@{
    ViewBag.Title = "Edit";
}

<h2>Edit Staff</h2>

@Html.ValidationSummary(false, "", new { @class = "text-danger" })

@using (Html.BeginForm("Edit", "Staffs", FormMethod.Post))
{
    @Html.HiddenFor(p => p.Staff.Id)
    <div class="form-group">
        @Html.LabelFor(p => p.Staff.Name)
        @Html.EditorFor(p => p.Staff.Name, new { htmlAttributes = new { @class = "form-control" } })
        @Html.ValidationMessageFor(p => p.Staff.Name, "", new { @class = "text-danger" })
    </div>
    <div class="form-group">
        @Html.LabelFor(p => p.Staff.StaffEmail)
        @Html.EditorFor(p => p.Staff.StaffEmail, new { htmlAttributes = new { @class = "form-control" } })
        @Html.ValidationMessageFor(p => p.Staff.StaffEmail, "", new { @class = "text-danger" })
    </div>
    <div class="form-group">
        @Html.LabelFor(p => p.Staff.PassEmail)
        @Html.TextBoxFor(p => p.Staff.PassEmail, new { @class = "form-control" })
        @Html.ValidationMessageFor(p => p.Staff.PassEmail, "", new { @class = "text-danger" })
    </div>
    <div class="form-group">
        @Html.LabelFor(p => p.Staff.Department.Name)
        @Html.DropDownListFor(p => p.Staff.DepartmentId,
         new SelectList(Model.Departments, "Id", "Name"),
         "Select Department Name",
         new { @class = "form-control" })
    </div>
    <button type="submit" class="btn btn-primary">Edit</button>
}
@Html.ActionLink("Back to Index", "Index")

FPTTraining0/Views/Staffs/Index.cshtml
@model IEnumerable<FPTTraining0.Models.Staff>

@{
    ViewBag.Title = "Index";
}

@if (User.IsInRole("admin") && Request.IsAuthenticated)
{
    @Html.ActionLink("Create a new Staff", "Create")
}

@using (Html.BeginForm("Index", "Staffs", FormMethod.Get))
{
    <p>
        Find by name: @Html.TextBox("SearchString")
        <input type="submit" value="Search" />
    </p>
}

<table class="table table-striped">
    <tr>
        <th>Id</th>
        <th>Staff Name</th>
        <th>Email</th>
        <th>Password Email</th>
        <th>Department</th>
        @if (User.IsInRole("admin"))
        {
            <th>Delete</th>
            <th>Edit</th>
        }
    </tr>
    @foreach (var staff in Model)
    {
<tr>
    <td>@staff.Id</td>
    <td>@staff.Name</td>
    <td>@staff.StaffEmail</td>
    <td>@staff.PassEmail</td>
    <td>@staff.Department.Name</td>
    @if (User.IsInRole("admin") && Request.IsAuthenticated)
    {
        <td>@Html.ActionLink("Delete this staff", "Delete", new { id = staff.Id })</td>
        <td>@Html.ActionLink("Edit this staff", "Edit", new { id = staff.Id })</td>
    }
</tr>
    }
</table>
@Html.ActionLink("Back to home", "Index", "Home")