FPTTraining0/Models/Trainee.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace FPTTraining0.Models
{
    public class Trainee
    {
        public int Id { get; set; }
        [Required]
        [DisplayName("Trainee Name")]
        public string Name { get; set; }
        [Required]
        [DisplayName("Trainee Email")]
        public string TraineeEmail { get; set; }
        [Required]
        [DisplayName("Password Email")]
        public string PassEmail { get; set; }
        [Required]
        [DisplayName("Year of Birth")]
        public string Birth { get; set; }
        [Required]
        public int CourseId  { get; set; }
        public Course Course { get; set; }
    }
}

FPTTraining0/Controllers/TraineesController.cs
using FPTTraining0.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Data.Entity;
using FPTTraining0.ViewModels;

namespace FPTTraining0.Controllers
{
    public class TraineesController : Controller
    {
		private ApplicationDbContext _context;
		public TraineesController()
		{
			_context = new ApplicationDbContext();
		}
		// GET: Trainee
		[HttpGet]
		public ActionResult Index(string searchString)
		{
			var trainees = _context.Trainees
			.Include(p => p.Course);

			if (!String.IsNullOrEmpty(searchString))
			{
				trainees = trainees.Where(
					s => s.Name.Contains(searchString) ||
					s.Course.Name.Contains(searchString));
			}

			return View(trainees.ToList());
		}

		[HttpGet]
		[Authorize(Roles = "staff")]
		public ActionResult Create()
		{
			var viewModel = new TraineeCourseViewModel
			{
				Courses = _context.Courses.ToList()
			};
			return View(viewModel);
		}

		[HttpPost]
		[Authorize(Roles = "staff")]
		public ActionResult Create(Trainee trainee)
		{
			if (!ModelState.IsValid)
			{
				return View();
			}

			if (_context.Trainees.Any(p => p.Name.Contains(trainee.Name)))
			{
				ModelState.AddModelError("Name", "Trainee Name Already Exists.");
				return View();
			}

			var newTrainee = new Trainee
			{
				Name = trainee.Name,
				TraineeEmail = trainee.TraineeEmail,
				PassEmail = trainee.PassEmail,
				Birth = trainee.Birth,
				CourseId = trainee.CourseId
			};

			_context.Trainees.Add(newTrainee);
			_context.SaveChanges();

			return RedirectToAction("Index");
		}

		[HttpGet]
		[Authorize(Roles = "staff")]

		public ActionResult Delete(int id)
		{
			var traineeInDb = _context.Trainees.SingleOrDefault(p => p.Id == id);

			if (traineeInDb == null)
			{
				return HttpNotFound();
			}

			_context.Trainees.Remove(traineeInDb);
			_context.SaveChanges();

			return RedirectToAction("Index");
		}

		[HttpGet]
		[Authorize(Roles = "staff")]

		public ActionResult Edit(int id)
		{
			var traineeInDb = _context.Trainees.SingleOrDefault(p => p.Id == id);

			if (traineeInDb == null)
			{
				return HttpNotFound();
			}

			var viewModel = new TraineeCourseViewModel
			{
				Trainee = traineeInDb,
				Courses = _context.Courses.ToList()
			};

			return View(viewModel);
		}

		[HttpPost]
		[Authorize(Roles = "staff")]

		public ActionResult Edit(Trainee trainee)
		{
			if (!ModelState.IsValid)
			{
				return View();
			}

			var traineeInDb = _context.Trainees.SingleOrDefault(p => p.Id == trainee.Id);

			if (traineeInDb == null)
			{
				return HttpNotFound();
			}

			traineeInDb.Name = trainee.Name;
			traineeInDb.TraineeEmail = trainee.TraineeEmail;
			traineeInDb.PassEmail = trainee.PassEmail;
			traineeInDb.Birth = trainee.Birth;
			traineeInDb.CourseId = trainee.CourseId;
			_context.SaveChanges();

			return RedirectToAction("Index");
		}
	}
}

FPTTraining0/Views/Trainees/Create.cshtml
@model FPTTraining0.ViewModels.TraineeCourseViewModel

@{
    ViewBag.Title = "Create";
}

<h2>Create a new Trainee</h2>

@Html.ValidationSummary(false, "", new { @class = "text-danger" })

@using (Html.BeginForm("Create", "Trainees", FormMethod.Post))
{
    <div class="form-group">
        @Html.LabelFor(p => p.Trainee.Name)
        @Html.TextBoxFor(p => p.Trainee.Name, new { @class = "form-control" })
        @Html.ValidationMessageFor(p => p.Trainee.Name, "", new { @class = "text-danger" })
    </div>
    <div class="form-group">
        @Html.LabelFor(p => p.Trainee.TraineeEmail)
        @Html.TextBoxFor(p => p.Trainee.TraineeEmail, new { @class = "form-control" })
        @Html.ValidationMessageFor(p => p.Trainee.TraineeEmail, "", new { @class = "text-danger" })
    </div>
    <div class="form-group">
        @Html.LabelFor(p => p.Trainee.PassEmail)
        @Html.TextBoxFor(p => p.Trainee.PassEmail, new { @class = "form-control" })
        @Html.ValidationMessageFor(p => p.Trainee.PassEmail, "", new { @class = "text-danger" })
    </div>
    <div class="form-group">
        @Html.LabelFor(p => p.Trainee.Birth)
        @Html.TextBoxFor(p => p.Trainee.Birth, new { @class = "form-control" })
        @Html.ValidationMessageFor(p => p.Trainee.Birth, "", new { @class = "text-danger" })
    </div>
    <div class="form-group">
        @Html.LabelFor(p => p.Trainee.Course.Name)
        @Html.DropDownListFor(p => p.Trainee.CourseId,
         new SelectList(Model.Courses, "Id", "Name"),
         "Select Course Name",
         new { @class = "form-control" })
    </div>
    <button type="submit" class="btn btn-primary">Create</button>
}
@Html.ActionLink("Back to Index", "Index")

FPTTraining0/Views/Trainees/Edit.cshtml
@model FPTTraining0.ViewModels.TraineeCourseViewModel

@{
    ViewBag.Title = "Edit";
}

<h2>Edit Trainee</h2>

@Html.ValidationSummary(false, "", new { @class = "text-danger" })

@using (Html.BeginForm("Edit", "Trainees", FormMethod.Post))
{
    @Html.HiddenFor(p => p.Trainee.Id)
    <div class="form-group">
        @Html.LabelFor(p => p.Trainee.Name)
        @Html.EditorFor(p => p.Trainee.Name, new { htmlAttributes = new { @class = "form-control" } })
        @Html.ValidationMessageFor(p => p.Trainee.Name, "", new { @class = "text-danger" })
    </div>
    <div class="form-group">
        @Html.LabelFor(p => p.Trainee.TraineeEmail)
        @Html.EditorFor(p => p.Trainee.TraineeEmail, new { htmlAttributes = new { @class = "form-control" } })
        @Html.ValidationMessageFor(p => p.Trainee.TraineeEmail, "", new { @class = "text-danger" })
    </div>
    <div class="form-group">
        @Html.LabelFor(p => p.Trainee.PassEmail)
        @Html.TextBoxFor(p => p.Trainee.PassEmail, new { @class = "form-control" })
        @Html.ValidationMessageFor(p => p.Trainee.PassEmail, "", new { @class = "text-danger" })
    </div>
    <div class="form-group">
        @Html.LabelFor(p => p.Trainee.Birth)
        @Html.TextBoxFor(p => p.Trainee.Birth, new { @class = "form-control" })
        @Html.ValidationMessageFor(p => p.Trainee.Birth, "", new { @class = "text-danger" })
    </div>
    <div class="form-group">
        @Html.LabelFor(p => p.Trainee.Course.Name)
        @Html.DropDownListFor(p => p.Trainee.Course,
         new SelectList(Model.Courses, "Id", "Name"),
         "Select Course Name",
         new { @class = "form-control" })
    </div>
    <button type="submit" class="btn btn-primary">Edit</button>
}
@Html.ActionLink("Back to Index", "Index")

FPTTraining0/Views/Trainees/Index.cshtml
@model IEnumerable<FPTTraining0.Models.Trainee>

@{
    ViewBag.Title = "Index";
}

<h2>Index Trainer</h2>
@Html.ActionLink("Create a new Trainee", "Create")
@using (Html.BeginForm("Index", "Trainees", FormMethod.Get))
{
    <p>
        Find by name: @Html.TextBox("SearchString")
        <input type="submit" value="Search" />
    </p>
}
<table class="table table-striped">
    <tr>
        <th>Id</th>
        <th>Trainee Name</th>
        <th>Email</th>
        <th>Password Email</th>
        <th>Year of Birth</th>
        <th>Course</th>
        @if (User.IsInRole("staff"))
        {
            <th>Delete</th>
            <th>Edit</th>
        }
    </tr>
    @foreach (var trainee in Model)
    {
<tr>
    <td>@trainee.Id</td>
    <td>@trainee.Name</td>
    <td>@trainee.TraineeEmail</td>
    <td>@trainee.PassEmail</td>
    <td>@trainee.Birth</td>
    <td>@trainee.Course.Name</td>
    <td>@Html.ActionLink("Delete this trainer", "Delete", new { id = trainee.Id })</td>
    <td>@Html.ActionLink("Edit this trainer", "Edit", new { id = trainee.Id })</td>
</tr>
    }
</table>
@Html.ActionLink("Back to home", "Index", "Home")